version: '3'

services:
  redis:
    image: redis
  webserver:
    build: ./webserver
    ports:
      - "80:80"
    volumes: 
      - ./webserver:/app
    depends_on:
      - redis
    env_file:
      - app.env
  modelserver:
    build: ./modelserver
    depends_on:
      - redis
    networks:
      - deployml_network
    volumes: 
      - ./modelserver:/app
    env_file:
      - app.env
    environment:
      - SERVER_SLEEP=0.25  # Time in ms between each poll by model server against Redis
      - BATCH_SIZE=32