version: '3'

services:
  redis:
    image: redis
    networks:
      - deployml_network

  modelserver:
    # image: ndtu1511/project_dsa_modelserver:model_2
    build: ./modelserver
    depends_on:
      - redis
    networks:
      - deployml_network
    volumes: 
      - ./modelserver:/app
    env_file:
      - app.env
    environment:
      - SERVER_SLEEP=0.25
      - BATCH_SIZE=32
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.role == worker

  webserver:
    # image: ndtu1511/project_dsa_webserver:web_2
    build: ./webserver
    ports:
      - "80:80"
    networks:
      - deployml_network
    volumes: 
      - ./webserver:/app
    depends_on:
      - redis
    env_file:
      - app.env
    environment:
      - CLIENT_SLEEP=0.25 
      - CLIENT_MAX_TRIES=100
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
    deployml_network: